# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_Query.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(495, 285)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 471, 81))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("font: 14pt \"华文楷体\";")
        self.groupBox.setObjectName("groupBox")
        self.dateTimeEdit_begin = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_begin.setGeometry(QtCore.QRect(180, 20, 194, 22))
        self.dateTimeEdit_begin.setStyleSheet("font: 14pt \"华文楷体\";")
        self.dateTimeEdit_begin.setObjectName("dateTimeEdit_begin")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(100, 50, 81, 16))
        self.label_2.setObjectName("label_2")
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_end.setGeometry(QtCore.QRect(180, 50, 194, 22))
        self.dateTimeEdit_end.setStyleSheet("font: 14pt \"华文楷体\";")
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.pushButton_querytime = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_querytime.setGeometry(QtCore.QRect(380, 20, 75, 51))
        self.pushButton_querytime.setObjectName("pushButton_querytime")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 471, 71))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("font: 14pt \"华文楷体\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_steelno = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_steelno.setGeometry(QtCore.QRect(180, 30, 191, 20))
        self.lineEdit_steelno.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_steelno.setObjectName("lineEdit_steelno")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(100, 30, 81, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_querysteelno = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_querysteelno.setGeometry(QtCore.QRect(380, 30, 75, 23))
        self.pushButton_querysteelno.setObjectName("pushButton_querysteelno")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 471, 71))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("font: 14pt \"华文楷体\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(100, 30, 81, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_squence = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_squence.setGeometry(QtCore.QRect(180, 30, 191, 20))
        self.lineEdit_squence.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_squence.setObjectName("lineEdit_squence")
        self.pushButton_querysquence = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_querysquence.setGeometry(QtCore.QRect(380, 30, 75, 23))
        self.pushButton_querysquence.setObjectName("pushButton_querysquence")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "查询窗口"))
        self.groupBox.setTitle(_translate("Form", "时间查询"))
        self.label.setText(_translate("Form", "起始时间："))
        self.label_2.setText(_translate("Form", "截至时间："))
        self.pushButton_querytime.setText(_translate("Form", "查询"))
        self.groupBox_2.setTitle(_translate("Form", "编号查询"))
        self.label_3.setText(_translate("Form", "钢板编号："))
        self.pushButton_querysteelno.setText(_translate("Form", "查询"))
        self.groupBox_3.setTitle(_translate("Form", "流水查询"))
        self.label_4.setText(_translate("Form", "流水编号："))
        self.pushButton_querysquence.setText(_translate("Form", "查询"))

