# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dlg_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2064, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("font: 14pt \"华文楷体\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_SteelImageMode = QtWidgets.QWidget()
        self.tab_SteelImageMode.setObjectName("tab_SteelImageMode")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_SteelImageMode)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_SteelImageTop = QtWidgets.QVBoxLayout()
        self.verticalLayout_SteelImageTop.setObjectName("verticalLayout_SteelImageTop")
        self.horizontalLayout_2.addLayout(self.verticalLayout_SteelImageTop)
        self.verticalLayout_SteelImageBottom = QtWidgets.QVBoxLayout()
        self.verticalLayout_SteelImageBottom.setObjectName("verticalLayout_SteelImageBottom")
        self.horizontalLayout_2.addLayout(self.verticalLayout_SteelImageBottom)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_SteelImageMode, "")
        self.tab_DistributionMode = QtWidgets.QWidget()
        self.tab_DistributionMode.setObjectName("tab_DistributionMode")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_DistributionMode)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_DistributionTop = QtWidgets.QVBoxLayout()
        self.verticalLayout_DistributionTop.setObjectName("verticalLayout_DistributionTop")
        self.verticalLayout_4.addLayout(self.verticalLayout_DistributionTop)
        self.verticalLayout_DistributionBottom = QtWidgets.QVBoxLayout()
        self.verticalLayout_DistributionBottom.setObjectName("verticalLayout_DistributionBottom")
        self.verticalLayout_4.addLayout(self.verticalLayout_DistributionBottom)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        # self.listWidget_DefectImg = QtWidgets.QListWidget(self.tab_DistributionMode)
        # self.listWidget_DefectImg.setObjectName("listWidget_DefectImg")
        # self.horizontalLayout_7.addWidget(self.listWidget_DefectImg)
        # self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_DistributionMode, "")
        self.tab_3DMode = QtWidgets.QWidget()
        self.tab_3DMode.setObjectName("tab_3DMode")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3DMode)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3DImg = QtWidgets.QVBoxLayout()
        self.verticalLayout_3DImg.setObjectName("verticalLayout_3DImg")
        self.gridLayout_4.addLayout(self.verticalLayout_3DImg, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3DMode, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_ContourImg = QtWidgets.QVBoxLayout()
        self.verticalLayout_ContourImg.setObjectName("verticalLayout_ContourImg")
        self.gridLayout_5.addLayout(self.verticalLayout_ContourImg, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEdit_MeasureLength = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_MeasureLength.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_MeasureLength.setReadOnly(True)
        self.lineEdit_MeasureLength.setObjectName("lineEdit_MeasureLength")
        self.horizontalLayout_9.addWidget(self.lineEdit_MeasureLength)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_MeasureWidth = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_MeasureWidth.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_MeasureWidth.setReadOnly(True)
        self.lineEdit_MeasureWidth.setObjectName("lineEdit_MeasureWidth")
        self.horizontalLayout_8.addWidget(self.lineEdit_MeasureWidth)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.lineEdit_BaseWidth = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_BaseWidth.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_BaseWidth.setReadOnly(True)
        self.lineEdit_BaseWidth.setObjectName("lineEdit_BaseWidth")
        self.horizontalLayout_11.addWidget(self.lineEdit_BaseWidth)
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.lineEdit_MeasureCurvature = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_MeasureCurvature.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_MeasureCurvature.setReadOnly(True)
        self.lineEdit_MeasureCurvature.setObjectName("lineEdit_MeasureCurvature")
        self.horizontalLayout_16.addWidget(self.lineEdit_MeasureCurvature)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_18.addWidget(self.lineEdit)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_18.addWidget(self.label_26)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_19.addWidget(self.lineEdit_2)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_20.addWidget(self.label_25)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_20.addWidget(self.lineEdit_3)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_20.addWidget(self.label_28)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_17.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_24.addWidget(self.label_40)
        self.lineEdit_CutAngle = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_CutAngle.setObjectName("lineEdit_CutAngle")
        self.horizontalLayout_24.addWidget(self.lineEdit_CutAngle)
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_24.addWidget(self.label_41)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_39 = QtWidgets.QLabel(self.tab)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_26.addWidget(self.label_39)
        self.lineEdit_MainDiagonalLength = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_MainDiagonalLength.setObjectName("lineEdit_MainDiagonalLength")
        self.horizontalLayout_26.addWidget(self.lineEdit_MainDiagonalLength)
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_26.addWidget(self.label_43)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_25.addWidget(self.label_42)
        self.lineEdit_AuxiliaryDiagonalLength = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_AuxiliaryDiagonalLength.setObjectName("lineEdit_AuxiliaryDiagonalLength")
        self.horizontalLayout_25.addWidget(self.lineEdit_AuxiliaryDiagonalLength)
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_25.addWidget(self.label_44)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_28.addWidget(self.label_45)
        self.lineEdit_TopEdgeLength = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_TopEdgeLength.setObjectName("lineEdit_TopEdgeLength")
        self.horizontalLayout_28.addWidget(self.lineEdit_TopEdgeLength)
        self.label_47 = QtWidgets.QLabel(self.tab)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_28.addWidget(self.label_47)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_46 = QtWidgets.QLabel(self.tab)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_27.addWidget(self.label_46)
        self.lineEdit_BottomEdgeLength = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_BottomEdgeLength.setObjectName("lineEdit_BottomEdgeLength")
        self.horizontalLayout_27.addWidget(self.lineEdit_BottomEdgeLength)
        self.label_48 = QtWidgets.QLabel(self.tab)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_27.addWidget(self.label_48)
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_17.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_BaseCutHead = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_BaseCutHead.setStyleSheet("font: 14pt \"华文楷体\";\n"
"color: rgb(255, 0, 0);")
        self.lineEdit_BaseCutHead.setReadOnly(True)
        self.lineEdit_BaseCutHead.setObjectName("lineEdit_BaseCutHead")
        self.horizontalLayout_10.addWidget(self.lineEdit_BaseCutHead)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.spinBox_AddCutHead = QtWidgets.QSpinBox(self.tab)
        self.spinBox_AddCutHead.setStyleSheet("font: 14pt \"华文楷体\";\n"
"color: rgb(0, 255, 0);")
        self.spinBox_AddCutHead.setObjectName("spinBox_AddCutHead")
        self.horizontalLayout_10.addWidget(self.spinBox_AddCutHead)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setStyleSheet("font: 14pt \"华文楷体\";\n"
"")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.lineEdit_BaseCutTail = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_BaseCutTail.setStyleSheet("font: 14pt \"华文楷体\";\n"
"color: rgb(255, 0, 0);")
        self.lineEdit_BaseCutTail.setReadOnly(True)
        self.lineEdit_BaseCutTail.setObjectName("lineEdit_BaseCutTail")
        self.horizontalLayout_12.addWidget(self.lineEdit_BaseCutTail)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.spinBox_AddCutTail = QtWidgets.QSpinBox(self.tab)
        self.spinBox_AddCutTail.setStyleSheet("font: 14pt \"华文楷体\";\n"
"color: rgb(0, 255, 0);")
        self.spinBox_AddCutTail.setObjectName("spinBox_AddCutTail")
        self.horizontalLayout_12.addWidget(self.spinBox_AddCutTail)
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_15.addWidget(self.label_36)
        self.lineEdit_BaseCutLeftEdge = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_BaseCutLeftEdge.setStyleSheet("font: 14pt \"华文楷体\";\n"
"color: rgb(255, 0, 0);")
        self.lineEdit_BaseCutLeftEdge.setReadOnly(True)
        self.lineEdit_BaseCutLeftEdge.setObjectName("lineEdit_BaseCutLeftEdge")
        self.horizontalLayout_15.addWidget(self.lineEdit_BaseCutLeftEdge)
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_15.addWidget(self.label_37)
        self.spinBox_AddCutLeftEdge = QtWidgets.QSpinBox(self.tab)
        self.spinBox_AddCutLeftEdge.setStyleSheet("font: 14pt \"华文楷体\";\n"
"color: rgb(0, 255, 0);")
        self.spinBox_AddCutLeftEdge.setObjectName("spinBox_AddCutLeftEdge")
        self.horizontalLayout_15.addWidget(self.spinBox_AddCutLeftEdge)
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_15.addWidget(self.label_38)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.lineEdit_BaseCutRightEdge = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_BaseCutRightEdge.setStyleSheet("font: 14pt \"华文楷体\";\n"
"color: rgb(255, 0, 0);")
        self.lineEdit_BaseCutRightEdge.setReadOnly(True)
        self.lineEdit_BaseCutRightEdge.setObjectName("lineEdit_BaseCutRightEdge")
        self.horizontalLayout_13.addWidget(self.lineEdit_BaseCutRightEdge)
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        self.spinBox_AddCutRightEdge = QtWidgets.QSpinBox(self.tab)
        self.spinBox_AddCutRightEdge.setStyleSheet("font: 14pt \"华文楷体\";\n"
"color: rgb(0, 255, 0);")
        self.spinBox_AddCutRightEdge.setObjectName("spinBox_AddCutRightEdge")
        self.horizontalLayout_13.addWidget(self.spinBox_AddCutRightEdge)
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_13.addWidget(self.label_35)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.lineEdit_MarginLength = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_MarginLength.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_MarginLength.setReadOnly(True)
        self.lineEdit_MarginLength.setObjectName("lineEdit_MarginLength")
        self.horizontalLayout_14.addWidget(self.lineEdit_MarginLength)
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_23.addWidget(self.label_33)
        self.lineEdit_MarginWidth = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_MarginWidth.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_MarginWidth.setReadOnly(True)
        self.lineEdit_MarginWidth.setObjectName("lineEdit_MarginWidth")
        self.horizontalLayout_23.addWidget(self.lineEdit_MarginWidth)
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_23.addWidget(self.label_34)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_21.addWidget(self.label_29)
        self.lineEdit_PlanLength = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_PlanLength.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_PlanLength.setReadOnly(False)
        self.lineEdit_PlanLength.setObjectName("lineEdit_PlanLength")
        self.horizontalLayout_21.addWidget(self.lineEdit_PlanLength)
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_21.addWidget(self.label_30)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_22.addWidget(self.label_31)
        self.lineEdit_PlanWidth = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_PlanWidth.setStyleSheet("font: 14pt \"华文楷体\";")
        self.lineEdit_PlanWidth.setReadOnly(False)
        self.lineEdit_PlanWidth.setObjectName("lineEdit_PlanWidth")
        self.horizontalLayout_22.addWidget(self.lineEdit_PlanWidth)
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_22.addWidget(self.label_32)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.pushButton_SetPlan = QtWidgets.QPushButton(self.tab)
        self.pushButton_SetPlan.setStyleSheet("font: 14pt \"华文楷体\";")
        self.pushButton_SetPlan.setObjectName("pushButton_SetPlan")
        self.verticalLayout_2.addWidget(self.pushButton_SetPlan)
        self.horizontalLayout_17.addLayout(self.verticalLayout_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.graphicsView_DefectShow = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_DefectShow.setObjectName("graphicsView_DefectShow")
        self.verticalLayout.addWidget(self.graphicsView_DefectShow)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_CurrSeqNo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_CurrSeqNo.setFont(font)
        self.label_CurrSeqNo.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_CurrSeqNo.setObjectName("label_CurrSeqNo")
        self.horizontalLayout_3.addWidget(self.label_CurrSeqNo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_CurrSteelNo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_CurrSteelNo.setFont(font)
        self.label_CurrSteelNo.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_CurrSteelNo.setObjectName("label_CurrSteelNo")
        self.horizontalLayout_4.addWidget(self.label_CurrSteelNo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label_CurrDetectDateTime = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_CurrDetectDateTime.setFont(font)
        self.label_CurrDetectDateTime.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_CurrDetectDateTime.setObjectName("label_CurrDetectDateTime")
        self.horizontalLayout_5.addWidget(self.label_CurrDetectDateTime)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.label_CurrSteelType = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_CurrSteelType.setFont(font)
        self.label_CurrSteelType.setStyleSheet("font: 14pt \"华文楷体\";")
        self.label_CurrSteelType.setObjectName("label_CurrSteelType")
        self.horizontalLayout_6.addWidget(self.label_CurrSteelType)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.tableWidget_SteelList = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_SteelList.setStyleSheet("font: 14pt \"华文楷体\";")
        self.tableWidget_SteelList.setObjectName("tableWidget_SteelList")
        self.tableWidget_SteelList.setColumnCount(0)
        self.tableWidget_SteelList.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_SteelList)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2064, 23))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuery = QtWidgets.QAction(MainWindow)
        self.actionQuery.setObjectName("actionQuery")
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionQuery)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SteelImageMode), _translate("MainWindow", "图像缺陷展示模式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DistributionMode), _translate("MainWindow", "分布图缺陷展示模式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3DMode), _translate("MainWindow", "3D缺陷展示模式"))
        self.label_8.setText(_translate("MainWindow", "【测量长度】："))
        self.label_14.setText(_translate("MainWindow", "单位（mm）"))
        self.label_6.setText(_translate("MainWindow", "【测量宽度】："))
        self.label_15.setText(_translate("MainWindow", "单位（mm）"))
        self.label_5.setText(_translate("MainWindow", "【基准宽度】："))
        self.label_20.setText(_translate("MainWindow", "单位（mm）"))
        self.label_13.setText(_translate("MainWindow", "【钢板曲率】："))
        self.label_16.setText(_translate("MainWindow", "单位（mm）"))
        self.label_23.setText(_translate("MainWindow", "【头部去弧】："))
        self.label_26.setText(_translate("MainWindow", "单位（mm）"))
        self.label_24.setText(_translate("MainWindow", "【尾部去弧】："))
        self.label_27.setText(_translate("MainWindow", "单位（mm）"))
        self.label_25.setText(_translate("MainWindow", "【板中长度】："))
        self.label_28.setText(_translate("MainWindow", "单位（mm）"))
        self.label_40.setText(_translate("MainWindow", "【方板切割弧形角度】："))
        self.label_41.setText(_translate("MainWindow", "单位（度°）"))
        self.label_39.setText(_translate("MainWindow", "【方板主对角线长度】："))
        self.label_43.setText(_translate("MainWindow", "单位（mm）"))
        self.label_42.setText(_translate("MainWindow", "【方板辅对角线长度】："))
        self.label_44.setText(_translate("MainWindow", "单位（mm）"))
        self.label_45.setText(_translate("MainWindow", "【方板长度---上边侧】："))
        self.label_47.setText(_translate("MainWindow", "单位（mm）"))
        self.label_46.setText(_translate("MainWindow", "【方板长度---下边侧】："))
        self.label_48.setText(_translate("MainWindow", "单位（mm）"))
        self.label_7.setText(_translate("MainWindow", "【头部切除范围】："))
        self.label_9.setText(_translate("MainWindow", "+"))
        self.label_17.setText(_translate("MainWindow", "单位（mm）"))
        self.label_10.setText(_translate("MainWindow", "【尾部切除范围】："))
        self.label_12.setText(_translate("MainWindow", "+"))
        self.label_18.setText(_translate("MainWindow", "单位（mm）"))
        self.label_36.setText(_translate("MainWindow", "【左边切除范围】："))
        self.label_37.setText(_translate("MainWindow", "+"))
        self.label_38.setText(_translate("MainWindow", "单位（mm）"))
        self.label_19.setText(_translate("MainWindow", "【右边切除范围】："))
        self.label_22.setText(_translate("MainWindow", "+"))
        self.label_35.setText(_translate("MainWindow", "单位（mm）"))
        self.label_11.setText(_translate("MainWindow", "【长度余量】："))
        self.label_21.setText(_translate("MainWindow", "单位（mm）"))
        self.label_33.setText(_translate("MainWindow", "【宽度余量】："))
        self.label_34.setText(_translate("MainWindow", "单位（mm）"))
        self.label_29.setText(_translate("MainWindow", "【计划长度】："))
        self.label_30.setText(_translate("MainWindow", "单位（mm）"))
        self.label_31.setText(_translate("MainWindow", "【计划宽度】："))
        self.label_32.setText(_translate("MainWindow", "单位（mm）"))
        self.pushButton_SetPlan.setText(_translate("MainWindow", "设置计划"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "轮廓分析优化剪切"))
        self.label.setText(_translate("MainWindow", "【流水序号】："))
        self.label_CurrSeqNo.setText(_translate("MainWindow", "******"))
        self.label_2.setText(_translate("MainWindow", "【钢板编号】："))
        self.label_CurrSteelNo.setText(_translate("MainWindow", "******"))
        self.label_3.setText(_translate("MainWindow", "【检测时间】："))
        self.label_CurrDetectDateTime.setText(_translate("MainWindow", "******"))
        self.label_4.setText(_translate("MainWindow", "【钢种信息】："))
        self.label_CurrSteelType.setText(_translate("MainWindow", "******"))
        self.menu_File.setTitle(_translate("MainWindow", "文件"))
        self.menu_Edit.setTitle(_translate("MainWindow", "编辑"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionQuery.setText(_translate("MainWindow", "查询"))

